server:
  port: 8083
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books
    username: root
    password: pass@word1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher